version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile

    container_name: backend
    volumes:
      - backend_data:/app/data
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - GO_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  backend_data:
